### ISSUE TITLE
Readme tips

### ISSUE THREAD

**Issue by CountNick** [Ramon96/frontend-data#1]
Hi there:clown_face:

You're of to a great start with the Readme! 

Some tips: 
:sos: Maybe add some more visuals about the supported features?
:sos: Maybe add a link to a live demo of your application?
:sos: Maybe add some more information about the data you used like:
* the query
* empty values
🆘 Maybe add some more overal information about you're concept in a engaging little story?
🆘 There's a spelling mistake in the readme "Upcomming features" should be upcoming

Already great: 
🎉 Nice visual!

**Comment by Ramon96** [comment]
Thanks men
